version: '3.8'
services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: chatbot
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

